version: '3.4'


services:
  rabbit:
    image: rabbitmq:3-management-alpine

  systema:
    image: ${DOCKER_REGISTRY-}systema
    build:
      context: .
      dockerfile: SystemA/Dockerfile


  systemb:
    image: ${DOCKER_REGISTRY-}systemb
    build:
      context: .
      dockerfile: SystemB/Dockerfile

       
