version: '3.4'

services:
  tcpdump:
    image: kaazing/tcpdump
    network_mode: "host"
    volumes:
      - ./tcpdump:/tcpdump
  
  rabbit:
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbit", "5672" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_VHOST=RabitHole
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  systema:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

   
  systemb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


